/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ffpyWUh4Lmx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Arimo } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Home() {
  return (
    <div>
      <section className="bg-primary py-20 text-primary-foreground">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid items-center gap-8 md:grid-cols-2">
            <div>
              <h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
                Unicum Plus
              </h1>
              <p className="mt-6 text-lg leading-8">
                Dynamic milkchoco cheat tools. It have many features that provide in-game api as electron web services.
                This page is for the purpose of providing more features of the application.
              </p>
            </div>
            <div className="flex justify-center">
              <img
                src="/placeholder.svg"
                alt="Acme Inc. Logo"
                width={600}
                height={300}
                className="rounded-full"
                style={{ aspectRatio: "600/300", objectFit: "cover" }}
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-8 text-3xl font-bold tracking-tight">Our Products</h2>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <ProductCard title="Tokens" description="Purchase tokens to use this application." image="/placeholder.svg" />
            <ProductCard title="Plugins" description="It provides more technical game APIs such as server-controller, graphic displayer." image="/placeholder.svg" />
            <ProductCard title="Record Datas" description="All datas from in-game recorded files such as replays, other informations." image="/placeholder.svg" />
          </div>
        </div>
      </section>
    </div>
  )
}

function ProductCard(props:{
  title:string;
  description:string;
  image:string;
}){
  return <div className="rounded-lg bg-card p-4 shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl flex flex-col justify-center items-center gap-2 select-none cursor-pointer">
    <img
      src={props.image}
      alt={props.title}
      width={400}
      height={250}
      className="mb-2 rounded-lg object-cover"
      style={{ aspectRatio: "400/250", objectFit: "cover" }}
    />
    <h3 className="text-xl font-bold w-full">{props.title}</h3>
    <p className="text-muted-foreground w-full">{props.description}</p>
  </div>
}